scraping/api/urls.py
from .views import *
from rest_framework import routers


router = routers.DefaultRouter()
router.register(r'cities', CityListAPIView)
router.register(r'specialties', SpecialtyListAPIView)
router.register(r'vacancies', VacancyListAPIView)

urlpatterns = []
urlpatterns += router.urls

vacancy/urls.py
# from django.conf.urls import url
from django.urls import re_path, path, include
from django.contrib import admin
from scraping.views import *
from subscribers import views

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^api/', include('scraping.api.urls')),
    re_path(r'^update/$', views.update_subscriber, name='update'),
    re_path(r'^login/$', views.login_subscriber, name='login'),
    re_path(r'^contact/$', views.contact_admin, name='contact'),
    re_path(r'^list/', vacancy_list, name='list'),
    re_path(r'^subscribe/$', views.SubscriberCreate.as_view(), name='subscribe'),
    path('', home, name='home'),
    # url(r'^', home, name='home'),
    
]

scraping/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField

class City(models.Model):
    name = models.CharField(max_length=50, verbose_name='Город')
    slug = models.SlugField(blank=True)
    class Meta:
        verbose_name = 'Город'
        verbose_name_plural = 'Города'
        ordering = ['name']

    def __str__(self):
        return self.name
        

class Site(models.Model):
    name = models.CharField(max_length=50, verbose_name='Название сайта для поиска')
    
    class Meta:
        verbose_name = 'Сайт'
        verbose_name_plural = 'Сайты'
        ordering = ['name']

    def __str__(self):
        return self.name
        

class Specialty(models.Model):
    name = models.CharField(max_length=50, verbose_name='Специальность')
    slug = models.SlugField(blank=True)
    
    
    class Meta:
        verbose_name = 'Специальность'
        verbose_name_plural = 'Специальности'
        ordering = ['name']

    def __str__(self):
        return self.name
 
        
class Url(models.Model):
    city = models.ForeignKey(City, verbose_name='Город', on_delete=models.CASCADE)
    site = models.ForeignKey(Site, verbose_name='Название сайта для поиска', on_delete=models.CASCADE)
    specialty = models.ForeignKey(Specialty, verbose_name='Специальность', on_delete=models.CASCADE)
    address = models.URLField(max_length=250, verbose_name='url')
    
    class Meta:
        verbose_name = 'Адрес для поиска'
        verbose_name_plural = 'Адреса для поиска'
        ordering = ['specialty', 'city']

    def __str__(self):
        return 'Специальность {} в г. {} на сайте {}'.format(self.specialty, self.city, self.site)
                

class Vacancy(models.Model):
    title = models.CharField(max_length=250, verbose_name='Заголовок вакансии')
    url = models.CharField(max_length=250, verbose_name='Интернет адрес вакансии', unique=True, default=None)
    description = models.TextField(verbose_name='Описание вакансии', blank=True)
    company = models.CharField(max_length=250, verbose_name='Вакансия от компании', blank=True)
    city = models.ForeignKey(City, verbose_name='Город', on_delete=models.CASCADE)
    specialty = models.ForeignKey(Specialty, verbose_name='Специальность', on_delete=models.CASCADE)
    timestamp = models.DateField(auto_now_add=True)
    
    class Meta:
        verbose_name = 'Вакансия'
        verbose_name_plural = 'Вакансии'
        ordering = ['-timestamp']

    def __str__(self):
        return self.title


class Error(models.Model):
    data = JSONField()
    timestamp = models.DateField(auto_now_add=True)
    
    class Meta:
        verbose_name = 'Ошибки скрапинга'
        verbose_name_plural = 'Ошибки скрапинга'
        ordering = ['-timestamp']

    def __str__(self):
        return self.timestamp.strftime('%Y-%m-%d')

scraping/forms.py
from django import forms
from scraping.models import Specialty, City

class FindVacancyForm(forms.Form):
    city = forms.ModelChoiceField(label='Город', queryset=City.objects.all(),
                                     widget=forms.Select(attrs={"class": 'form-control js-example-basic-single'}))
    specialty = forms.ModelChoiceField(label='Специальность', queryset=Specialty.objects.all(),
                                     widget=forms.Select(attrs={"class": 'form-control js-example-basic-single'}))
 

scraping/api/views.py
# -*- coding: utf-8 -*-
import datetime
from rest_framework import viewsets
from scraping.models import City, Specialty, Vacancy

from rest_framework.response import Response
from rest_framework.decorators import action
# from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from .serializers import * 

TODAY = datetime.date.today()


class CityListAPIView(viewsets.ModelViewSet):
    
    queryset = City.objects.all()
    serializer_class = CitySerializer
    

class SpecialtyListAPIView(viewsets.ModelViewSet):
    
    queryset = Specialty.objects.all()
    serializer_class = SpecialtySerializer
       

class VacancyListAPIView(viewsets.ModelViewSet):
    """ 
    
        ?city=kyiv&specialty=python
        
        city - slug for city filter;
        specialty - filter for specialty;
        
        
    """
    queryset = Vacancy.objects.all()
    serializer_class = VacancySerializer
    
    def get_queryset(self):
        req = self.request
        city_slug = req.query_params.get('city')
        specialty_slug = req.query_params.get('specialty')
        qs = None
        
        if city_slug and specialty_slug:
            city, specialty = None, None
            city = City.objects.filter(slug=city_slug).first()
            if not city:
                city = City.objects.filter(slug=specialty_slug).first()
            specialty = Specialty.objects.filter(slug=specialty_slug).first()
            if not specialty:
                specialty = Specialty.objects.filter(slug=city_slug).first()
            period = TODAY - datetime.timedelta(1)
            if city and specialty:
                qs = Vacancy.objects.filter(city=city, specialty=specialty, 
                                timestamp__gte=period)
             
        self.queryset = qs    
        return self.queryset

scraping/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
import datetime

from .models import *
from .forms import FindVacancyForm


def home(request):
    form = FindVacancyForm
    return render(request, 'scraping/home.html', {'form': form})


def vacancy_list(request):
    form = FindVacancyForm
    if request.GET:
        try:
            city_id = int(request.GET.get('city'))
            specialty_id = int(request.GET.get('specialty'))
        except ValueError:
            raise Http404("Страница не найдена")
        context = {}
        context['form'] = form
        qs = Vacancy.objects.filter(city=city_id, specialty=specialty_id)
        if qs:
            context['object_list'] = qs
            context['city_name'] = qs[0].city.name
            context['specialty_name'] = qs[0].specialty.name
                                
        return render(request, 'scraping/list.html', context)

    return render(request, 'scraping/list.html', {'form': form,})

        

scraping/templates/scraping/home.html
{% extends 'base.html' %}
{%load static%}
{% block title %}Вакансии{% endblock %}

{% block content %}
<div  class="container">
   <div class="row">
        <div class="col-md-10 mx-auto">
        <h1 class="text-center">Сервис по сбору вакансий с сайтов по поиску работы</h1>
        <p class=" text-left"> Вакансии в сфере IT  размещаются на большинстве украинских сайтах по поиску работы. Но наиболее активно и более полно их публикуют, лишь на некоторых из них. Каждый день эти сайты анализируются на предмет новых вакансий, согласно запросов от подпсчиков - в каких городах и по какой специальности искать. Все новые вакансии, которые были опубликованы на этих сайтах за последние сутки,  записываются в БД сервиса и рассылаюстя подписчикам, согласно их предпочтений. Вы можете просмартивать актуальные вакансии, просто выбрав необходимый город и специальность. Или, пройдя несложную <a href="{% url 'subscribe' %}"> регистрацию</a>, получать на e-mail каждый день письмо со списком новых вакансий за последние сутки по выбранной Вами специальности.</p>
        </div>
    </div>
    <hr>
   <div class="row">
        <div class="col-md-8 mx-auto ">
            <h4> Сохраненные вакансии за последнюю неделю</h3>
            <form class="update-data-form" action="{% url 'list' %}" method="get">
                <div class="row my-4">
                    <div class="col-md-4 text-right">
                        <label for="id_city">Город:</label>
                    </div>
                    <div class="col-md-8 ">
                        {{form.city}}
                    </div>
                </div>
                <div class="row my-4">
                    <div class="col-md-4 text-right">
                        <label for="id_specialty">Специальность:</label>
                    </div>
                    <div class="col-md-8 ">
                        {{form.specialty}}
                    </div>
                </div>
                <button type="submit" class='btn btn-success ' >Показать</button>
            </form>
               
    
        </div>
    </div>
    
</div>
{% endblock %}

scraping/templates/scraping/list.html
{% extends 'base.html' %}
{%load static%}
{% block title %}Результаты поиска{% endblock %}

{% block content %}
<div  class="container">
   <div class="row">
        <div class="col-md-10 text-left">
        
            {% if object_list %}
                <h3 class="text-center"> 
                    Вакансии по запросу: город - {{city_name}}, 
                    специальность -{{specialty_name}}
                </h3>
                <br/><hr><br/>
                {% for object in object_list %}
                    <a href="{{ object.url }}" target="_blank">{{ object.title }} </a>
                    <p>{{ object.description }} </p>
                    <p><small>Вакансия от компании: {{ object.company }}  , 
                    размещена {{ object.timestamp| date:"SHORT_DATE_FORMAT" }} </small></p>
                    <hr>
                {% endfor %}
            {% else %}
                <h2 class="text-center"> По Вашему запросу ничего не найдено.</h2>
            {% endif %}
        </div>
    </div>


    
  
        <div class="col-md-7 mx-3 ">
           
             <form class="update-data-form" action="{% url 'list' %}" method="get">
                <div class="row my-4">
                    <div class="col-md-4 text-right">
                        <label for="id_city">Город:</label>
                    </div>
                    <div class="col-md-8 ">
                        {{form.city}}
                    </div>
                </div>
                <div class="row my-4">
                    <div class="col-md-4 text-right">
                        <label for="id_specialty">Специальность:</label>
                    </div>
                    <div class="col-md-8 ">
                        {{form.specialty}}
                    </div>
                </div>
          
                <button type="submit" class='btn btn-success ' >Показать</button>
            </form>
               
    
        </div>
   
    
</div>
{% endblock %}